[project]
name = "kingship-auth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "django-oauth-toolkit>=3.0.1",
    "pyjwt>=2.10.1",
]
